const projects = [
  {
    id: 1,
    clientId: 101,
    name: "E-commerce Platform",
    description: "Development of a scalable e-commerce platform with payment integration.",
    status: "In Progress",
  },
  {
    id: 2,
    clientId: 102,
    name: "Hospital Management Dashboard",
    description: "A dashboard to manage patient records, appointments, and staff schedules.",
    status: "Completed",
  },
  {
    id: 3,
    clientId: 103,
    name: "Portfolio Website",
    description: "A responsive and visually appealing portfolio website for a graphic designer.",
    status: "Pending",
  },
  {
    id: 4,
    clientId: 104,
    name: "Mobile App for Fitness Tracking",
    description: "A cross-platform mobile application for tracking workouts and progress.",
    status: "In Progress",
  },
  {
    id: 5,
    clientId: 105,
    name: "Restaurant Reservation System",
    description: "A web application for booking tables at restaurants with real-time availability.",
    status: "On Hold",
  },
  {
    id: 6,
    clientId: 106,
    name: "Real Estate Listings API",
    description: "API for fetching and managing real estate property listings.",
    status: "Completed",
  },
  {
    id: 7,
    clientId: 107,
    name: "Learning Management System",
    description: "Development of an LMS for online courses and assessments.",
    status: "In Progress",
  },
  {
    id: 8,
    clientId: 108,
    name: "Social Media Analytics Tool",
    description: "Tool for analyzing and reporting social media performance metrics.",
    status: "Pending",
  },
  {
    id: 9,
    clientId: 109,
    name: "CRM Integration for Marketing",
    description: "Integration of CRM software to streamline marketing campaigns.",
    status: "On Hold",
  },
  {
    id: 10,
    clientId: 110,
    name: "Chatbot for Customer Support",
    description: "AI-powered chatbot to handle common customer queries and support tickets.",
    status: "Completed",
  },
];
const clients = [
  {
    id: 101,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
  },
  {
    id: 102,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+9876543210",
  },
  {
    id: 103,
    name: "Mike Johnson",
    email: "mike.johnson@example.com",
    phone: "+1122334455",
  },
  {
    id: 104,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "+5566778899",
  },
  {
    id: 105,
    name: "Sarah Brown",
    email: "sarah.brown@example.com",
    phone: "+9988776655",
  },
  {
    id: 106,
    name: "Chris Wilson",
    email: "chris.wilson@example.com",
    phone: "+4455667788",
  },
  {
    id: 107,
    name: "Anna Martinez",
    email: "anna.martinez@example.com",
    phone: "+2233445566",
  },
  {
    id: 108,
    name: "David Lee",
    email: "david.lee@example.com",
    phone: "+6677889900",
  },
  {
    id: 109,
    name: "Sophia Clark",
    email: "sophia.clark@example.com",
    phone: "+3344556677",
  },
  {
    id: 110,
    name: "James Lewis",
    email: "james.lewis@example.com",
    phone: "+7788990011",
  },
];
module.exports = { projects, clients };
